HW2 implement unpack string function
antonkanevsky/go-hw-test pull request #2
Opened 2022-10-02 20:03 UTC by antonkanevsky

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-10-13 11:34 UTC, farir1408 requested changes

2022-10-13 11:34 UTC, farir1408 commented on hw02_unpack_string/unpack.go
> +			repCnt, _ := strconv.Atoi(string(s[i+1]))
Не стоит игнорировать ошибку, тем более её можно вернуть дальше.

2022-10-13 11:34 UTC, farir1408 commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
Попробуйте написать тест для данного кода с использованием русских букв

2022-10-13 11:36 UTC, farir1408 commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
Когда вы используете таким образом цикл по строке, то итерируетесь по байтам. Итерация с использованием range работает иначе.

2023-02-28 22:34 UTC, antonkanevsky commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
добавил тест, проблему понял, поправил

2023-02-28 22:36 UTC, antonkanevsky commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
`range` тут мне кажется неудобно использовать, т.к. по алгоритму нужно проверять очередной символ за текущим. переписал на итерирование по массиву рун, работает корректно!

2023-02-28 22:36 UTC, antonkanevsky commented on hw02_unpack_string/unpack.go
> +			repCnt, _ := strconv.Atoi(string(s[i+1]))
согласен, поправил

2023-03-09 19:44 UTC, farir1408 commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
Можно и через range, но хранить текущую и предыдущую руну.

2023-03-09 19:46 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение домашнего задания.
Красивый, лаконичный код. Если интересно, попробуйте переписать его таким образом, чтобы не аллоцировать отдельный слайс рун, а использовать 2 переменные, текущая и предыдущая руна, их будет достаточно чтобы постепенно распаковать строку.

Принято 10/10.

2023-03-09 19:46 UTC, farir1408 approved these changes

2023-03-09 19:53 UTC, antonkanevsky commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
А можно посмотреть решение-эталон по данному ДЗ?

2023-03-09 19:56 UTC, antonkanevsky commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
спасибо, попробую

2023-03-18 21:52 UTC, antonkanevsky commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(s); i++ {
@farir1408 Олег, приветствую! попробовал реализовать проход  по строке через range, код становится более запутанным и сложно читаемым. Не удалось. Можете скинуть реализацию?

2023-03-18 21:53 UTC, merged